### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by sventer** [jcward/vscode-hxcpp-debug#41] opened 2016-09-09 10:03 UTC
I update to VSCode 1.5.1 and the build & debug don't seem to work anymore. The progress indicator seems to sit in a loop and there is not feedback in the debug console.

I can build from the command line without a problem. I'm attaching a test project, hopefully the configuration is correct.

[wsclient.zip](https://github.com/jcward/vscode-hxcpp-debug/files/463711/wsclient.zip)

**Comment by twincannon** [comment] 2016-09-28 09:09
I can't seem to build `vscode-hxcpp-debug` at all right now, haxe.exe returns this:

`src/Main.hx:729: characters 18-22 : debugger.StringList has no field iterator
src/Main.hx:731: characters 19-23 : {+ indexOf : String -> Int } should be String
src/Main.hx:731: characters 19-23 : For function argument 'x'
src/Main.hx:749: characters 33-43 : Too many arguments
Press enter to exit...`

This is with a fresh haxelib upgrade, I'm not familiar with any recent changes

**Comment by jcward** [comment] 2016-09-29 14:54
Hi @sventer - I'll have to update to 1.5.1 and give it a try. It seems to be working with everything Haxe up-to-date, with my old VSCode 1.0.0 linux installation.

(@twincannon - you build issue, `src/Main.hx:729: characters 18-22 : debugger.StringList has no field iterator` was likely due to a need to update the hxcpp-debugger haxelib from git.)

**Comment by twincannon** [comment] 2016-09-29 16:47
@jcward - Yep, that was exactly it. (I previously deleted my comment as I realized it was actually off-topic, apologies!)

**Comment by Jarrio** [comment] 2016-10-10 20:54
I can confirm this issue is on vs code 1.5.0+, I have tried on windows and osx and the only way to get the debugger to start compiling is to downgrade back to 1.4.0.

**Comment by jcward** [comment] 2016-10-10 21:12
Thanks for the input. Note to self, here's the changelog: https://code.visualstudio.com/updates/v1_5 (supposedly only additions to the debug adapter protocol.)

**Comment by jcward** [comment] 2017-03-14 19:15
I believe this should be fixed along with #44.

**Closed by jcward** 2017-03-14 19:15 UTC
